minimal_mistakes_skin: "default"

locale: "en-US"
title: "Amber Moffett, Researcher"
title_separator: "-"
name: "Amber Moffett"
email: "moffett.amber@gmail.com"
description: "Researcher at Monash University and international development professional specializing in conflict-affected environments."
url: "https://moffettamber.github.io"
baseurl: ""
repository: "moffettamber/moffettamber.github.io"

breadcrumbs: false
words_per_minute: 200

search: true
search_full_content: false

atom_feed:
  hide: true

author:
  name: "Amber Moffett"
  avatar: "/assets/images/headshot.jpeg"
  bio: "Researcher at Monash University and international development professional specializing in conflict-affected environments."
  location: "Melbourne, Australia"
  links:
    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/files/Amber-Moffett-CV.pdf"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:email@example.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amber-moffett/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=xMiSajIAAAAJ"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0007-4921-8771"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Amber-Moffett"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:email@example.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amber-moffett/"

markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
